# Generated by Django 4.2.13 on 2024-05-18 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('reference', models.CharField(default=uuid.uuid4, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
    ]
