# Generated by Django 4.2.13 on 2024-05-18 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='for_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
