# Generated by Django 4.2.13 on 2024-05-23 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_transaction_for_ticket_alter_transaction_reference"),
        ("register", "0003_remove_participant_type_participant_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="name",
            new_name="firstname",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="has_paid",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="user",
        ),
        migrations.AddField(
            model_name="participant",
            name="address",
            field=models.CharField(default="Default", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="attendance_mode",
            field=models.CharField(
                choices=[
                    ("Camper", "Camper"),
                    ("Daily", "Daily"),
                    ("Streamer", "Streamer"),
                ],
                default="Camper",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="birthdate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="church_name",
            field=models.CharField(
                default="he Lord's Brethren Church International", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(default="default@mail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="health_issue",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="lastname",
            field=models.CharField(default="Name", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participant",
            name="reach",
            field=models.CharField(
                choices=[
                    ("Facebook", "Facebook"),
                    ("WhatsApp", "Whatsapp"),
                    ("Instagram", "Instagram"),
                    ("Church", "Church"),
                    ("Website", "Website"),
                    ("Outreach", "Outreach"),
                    ("Friend", "Friend"),
                ],
                default="Church",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="transaction",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.transaction",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="was_participant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="is_aware_of_convention",
            field=models.BooleanField(default=False),
        ),
    ]
