# Generated by Django 4.2.13 on 2024-06-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_participant_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='default@change.com', max_length=254),
            preserve_default=False,
        ),
    ]
