# Generated by Django 4.2.13 on 2024-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='reference',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='reference',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
