# Generated by Django 4.2.13 on 2024-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_participant_reference_partner_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
